print('Hello!')
print('My name is Scribe Bot.')
print("Welcome to the flu/viral patient ward. I'm here to record your history of present illness (HPI)!")
print("What's your name?")
name = input()
print('Nice to meet you, ' + name + '.')
print('Your responses will be stored so that the doctor can access them later.')
print('First, on a scale of 1-10, how much pain do you feel?')
pain_level = input()
print('Okay. Is your pain improving, stagnant, or worsening?')
improvement = input()
print('Then, is the pain intermittent or constant?')
consistency = input()
print('Noted. How would you describe the pain? Dull? Sharp? Or something else?')
pain_description = input()
print("Thank you for your cooperation today! Here is a summary of today's HPI.") 
print('Name: ' + name)
print('Pain level: ' + pain_level)
print('Pain progression: ' + improvement)
print('Consistency: ' + consistency)
print('Pain Description: ' + pain_description)
print('Thank you for your responses. The doctor will view them before visiting you. Wishing you a speedy recovery!')
