print('Hello!')
print('My name is Scribe Bot.')
print('Welcome to the flu/viral patient ward. I'm here to record your history of present illness (HPI)!')
print('What's your name?')
name = input()
print('Nice to meet you, ' + name + '.')
print('Your responses will be stored so that the doctor can access them later.')
print('Alright. How do you feel today? Sad? Happy? Or something else?')
emotion = input()
print('First, on a scale of 1-10, how much pain do you feel?')
pain_level = input()
print('Do you believe that your pain is improving?')
improvement = input()
print('Is the pain itermittent or constant?')
consistency = input()
print('How would you describe the pain? Dull? Sharp? Or something else?')
pain_description = input()
print('Thank you for your cooperation today! Here is a summary of today's HPI.') 
print('Name: ' + name)
print('Mood: ' + emotion)
print('Pain level: ' + pain_level)
print('Pain progression: ' + improvement)
print('Consistency: ' + consistency)
print('Pain Description: ' + pain_description)
print('Thank you for your responses, they will be viewed by the doctor before they come and meet you. Wishing you a speedy recovery!')
